#USED
PATH_TO_PHOTOS = '/home/pi/timelapse/photos/'
PHOTO_INTERVAL = 1
RESOLUTION = (2592, 1933)
ROTATION = 270
ISO = 0
USER_COMMENT = 'Doug Matheson - Timelapse'


#NOT USED
AWB_MODE = '' 
BRIGHTNESS = 50
CONTRAST = 0
EXPOSURE_MODE = '' 
IMAGE_EFFECT = ''
